// Generated by gencpp from file beginner_tutorials4/CalculateEuclidResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS4_MESSAGE_CALCULATEEUCLIDRESPONSE_H
#define BEGINNER_TUTORIALS4_MESSAGE_CALCULATEEUCLIDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials4
{
template <class ContainerAllocator>
struct CalculateEuclidResponse_
{
  typedef CalculateEuclidResponse_<ContainerAllocator> Type;

  CalculateEuclidResponse_()
    : euc_dist(0.0)  {
    }
  CalculateEuclidResponse_(const ContainerAllocator& _alloc)
    : euc_dist(0.0)  {
  (void)_alloc;
    }



   typedef double _euc_dist_type;
  _euc_dist_type euc_dist;





  typedef boost::shared_ptr< ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CalculateEuclidResponse_

typedef ::beginner_tutorials4::CalculateEuclidResponse_<std::allocator<void> > CalculateEuclidResponse;

typedef boost::shared_ptr< ::beginner_tutorials4::CalculateEuclidResponse > CalculateEuclidResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials4::CalculateEuclidResponse const> CalculateEuclidResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials4': ['/home/osman/catkin_ws/src/beginner_tutorials4/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce7a696b716cfcfa56765f88df435f62";
  }

  static const char* value(const ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce7a696b716cfcfaULL;
  static const uint64_t static_value2 = 0x56765f88df435f62ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials4/CalculateEuclidResponse";
  }

  static const char* value(const ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 euc_dist\n\
\n\
";
  }

  static const char* value(const ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.euc_dist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalculateEuclidResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials4::CalculateEuclidResponse_<ContainerAllocator>& v)
  {
    s << indent << "euc_dist: ";
    Printer<double>::stream(s, indent + "  ", v.euc_dist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS4_MESSAGE_CALCULATEEUCLIDRESPONSE_H
