// Generated by gencpp from file beginner_tutorials4/CalculateEuclid.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS4_MESSAGE_CALCULATEEUCLID_H
#define BEGINNER_TUTORIALS4_MESSAGE_CALCULATEEUCLID_H

#include <ros/service_traits.h>


#include <beginner_tutorials4/CalculateEuclidRequest.h>
#include <beginner_tutorials4/CalculateEuclidResponse.h>


namespace beginner_tutorials4
{

struct CalculateEuclid
{

typedef CalculateEuclidRequest Request;
typedef CalculateEuclidResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalculateEuclid
} // namespace beginner_tutorials4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials4::CalculateEuclid > {
  static const char* value()
  {
    return "97b5e3f1d4bdad95418fef5e31effaff";
  }

  static const char* value(const ::beginner_tutorials4::CalculateEuclid&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials4::CalculateEuclid > {
  static const char* value()
  {
    return "beginner_tutorials4/CalculateEuclid";
  }

  static const char* value(const ::beginner_tutorials4::CalculateEuclid&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials4::CalculateEuclidRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials4::CalculateEuclid > 
template<>
struct MD5Sum< ::beginner_tutorials4::CalculateEuclidRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials4::CalculateEuclid >::value();
  }
  static const char* value(const ::beginner_tutorials4::CalculateEuclidRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials4::CalculateEuclidRequest> should match 
// service_traits::DataType< ::beginner_tutorials4::CalculateEuclid > 
template<>
struct DataType< ::beginner_tutorials4::CalculateEuclidRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials4::CalculateEuclid >::value();
  }
  static const char* value(const ::beginner_tutorials4::CalculateEuclidRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials4::CalculateEuclidResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials4::CalculateEuclid > 
template<>
struct MD5Sum< ::beginner_tutorials4::CalculateEuclidResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials4::CalculateEuclid >::value();
  }
  static const char* value(const ::beginner_tutorials4::CalculateEuclidResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials4::CalculateEuclidResponse> should match 
// service_traits::DataType< ::beginner_tutorials4::CalculateEuclid > 
template<>
struct DataType< ::beginner_tutorials4::CalculateEuclidResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials4::CalculateEuclid >::value();
  }
  static const char* value(const ::beginner_tutorials4::CalculateEuclidResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS4_MESSAGE_CALCULATEEUCLID_H
