// Generated by gencpp from file beginner_tutorials4/CalculateEuclidRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS4_MESSAGE_CALCULATEEUCLIDREQUEST_H
#define BEGINNER_TUTORIALS4_MESSAGE_CALCULATEEUCLIDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials4
{
template <class ContainerAllocator>
struct CalculateEuclidRequest_
{
  typedef CalculateEuclidRequest_<ContainerAllocator> Type;

  CalculateEuclidRequest_()
    : point_one_x(0.0)
    , point_one_y(0.0)
    , point_two_x(0.0)
    , point_two_y(0.0)  {
    }
  CalculateEuclidRequest_(const ContainerAllocator& _alloc)
    : point_one_x(0.0)
    , point_one_y(0.0)
    , point_two_x(0.0)
    , point_two_y(0.0)  {
  (void)_alloc;
    }



   typedef double _point_one_x_type;
  _point_one_x_type point_one_x;

   typedef double _point_one_y_type;
  _point_one_y_type point_one_y;

   typedef double _point_two_x_type;
  _point_two_x_type point_two_x;

   typedef double _point_two_y_type;
  _point_two_y_type point_two_y;





  typedef boost::shared_ptr< ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CalculateEuclidRequest_

typedef ::beginner_tutorials4::CalculateEuclidRequest_<std::allocator<void> > CalculateEuclidRequest;

typedef boost::shared_ptr< ::beginner_tutorials4::CalculateEuclidRequest > CalculateEuclidRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials4::CalculateEuclidRequest const> CalculateEuclidRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials4': ['/home/osman/catkin_ws/src/beginner_tutorials4/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b52461afd157f53f1ce4e7d6ce3a9c67";
  }

  static const char* value(const ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb52461afd157f53fULL;
  static const uint64_t static_value2 = 0x1ce4e7d6ce3a9c67ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials4/CalculateEuclidRequest";
  }

  static const char* value(const ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 point_one_x\n\
float64 point_one_y\n\
float64 point_two_x\n\
float64 point_two_y\n\
";
  }

  static const char* value(const ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point_one_x);
      stream.next(m.point_one_y);
      stream.next(m.point_two_x);
      stream.next(m.point_two_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalculateEuclidRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials4::CalculateEuclidRequest_<ContainerAllocator>& v)
  {
    s << indent << "point_one_x: ";
    Printer<double>::stream(s, indent + "  ", v.point_one_x);
    s << indent << "point_one_y: ";
    Printer<double>::stream(s, indent + "  ", v.point_one_y);
    s << indent << "point_two_x: ";
    Printer<double>::stream(s, indent + "  ", v.point_two_x);
    s << indent << "point_two_y: ";
    Printer<double>::stream(s, indent + "  ", v.point_two_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS4_MESSAGE_CALCULATEEUCLIDREQUEST_H
