// Generated by gencpp from file beginner_tutorials4/Dist.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS4_MESSAGE_DIST_H
#define BEGINNER_TUTORIALS4_MESSAGE_DIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials4
{
template <class ContainerAllocator>
struct Dist_
{
  typedef Dist_<ContainerAllocator> Type;

  Dist_()
    : dist(0.0)  {
    }
  Dist_(const ContainerAllocator& _alloc)
    : dist(0.0)  {
  (void)_alloc;
    }



   typedef double _dist_type;
  _dist_type dist;





  typedef boost::shared_ptr< ::beginner_tutorials4::Dist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials4::Dist_<ContainerAllocator> const> ConstPtr;

}; // struct Dist_

typedef ::beginner_tutorials4::Dist_<std::allocator<void> > Dist;

typedef boost::shared_ptr< ::beginner_tutorials4::Dist > DistPtr;
typedef boost::shared_ptr< ::beginner_tutorials4::Dist const> DistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials4::Dist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials4::Dist_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials4': ['/home/osman/catkin_ws/src/beginner_tutorials4/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials4::Dist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials4::Dist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials4::Dist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials4::Dist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials4::Dist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials4::Dist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials4::Dist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f4fece6412db25720b2bab9f80b3473";
  }

  static const char* value(const ::beginner_tutorials4::Dist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f4fece6412db257ULL;
  static const uint64_t static_value2 = 0x20b2bab9f80b3473ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials4::Dist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials4/Dist";
  }

  static const char* value(const ::beginner_tutorials4::Dist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials4::Dist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 dist\n\
";
  }

  static const char* value(const ::beginner_tutorials4::Dist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials4::Dist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Dist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials4::Dist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials4::Dist_<ContainerAllocator>& v)
  {
    s << indent << "dist: ";
    Printer<double>::stream(s, indent + "  ", v.dist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS4_MESSAGE_DIST_H
